### ISSUE TITLE
Wrong equations for Rossler attractor

### ISSUE THREAD

**Issue by ShrirajHegde** [capitanov/chaospy#1]
Wrong equations for Rossler attractor

**Comment by hukenovs** [comment]
Equations are ok.

See: https://en.wikipedia.org/wiki/R%C3%B6ssler_attractor
```
dx/dt = -(y + z)
dy/dt = x + a * y
dz/dt = b + z * (x - c)
```

**Comment by ShrirajHegde** [comment]
sorry, I meant in [README](https://github.com/capitanov/chaospy/blob/master/README.rst#L54)

**Comment by hukenovs** [comment]
You are right. Thanks. I've fixed them.
